export const metadata = {
  title: "Admin Home - Zam Zam motors",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return <>
     <div className="flex justify-center items-center h-screen w-full">
      {children}
     </div>
  </>;
}
