import "./globals.css";
import SessionWrapper from "./components/SessionWrapper";

export const metadata = {
  title: "Zam Zam motors - Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
      </head>
      <body className="antialiased min-h-[100vh]">
        <SessionWrapper>{children}</SessionWrapper>
        <script
          src="https://kit.fontawesome.com/007a88595b.js"
          crossOrigin="anonymous"
        ></script>
      </body>
    </html>
  );
}
